use crate::store::models::{AccessList, AccessRule, Certificate, ProxyRule};

/// Generate an nginx HTTP server block for one or more rules sharing the same port+domain.
pub fn generate_server_block(
    rules: &[&ProxyRule],
    certs: &[Certificate],
    access_lists: &[(AccessList, Vec<AccessRule>)],
) -> String {
    if rules.is_empty() {
        return String::new();
    }

    let first = rules[0];
    let listen_port = first.listen_port;
    let domain = first.domain.as_deref().unwrap_or("_");

    let mut out = String::new();
    out.push_str("# Auto-generated by Meridian. Do not edit manually.\n");
    out.push_str("server {\n");

    // Listen directive
    let has_tls = first.tls_mode == "terminate";
    if has_tls {
        out.push_str(&format!("    listen {} ssl;\n", listen_port));
    } else {
        out.push_str(&format!("    listen {};\n", listen_port));
    }

    out.push_str(&format!("    server_name {};\n", domain));

    // TLS certificate
    if has_tls {
        if let Some(cert_id) = &first.certificate_id {
            if let Some(cert) = certs.iter().find(|c| &c.id == cert_id) {
                out.push_str(&format!("    ssl_certificate \"{}\";\n", cert.cert_path));
                out.push_str(&format!("    ssl_certificate_key \"{}\";\n", cert.key_path));
                out.push_str("    ssl_protocols TLSv1.2 TLSv1.3;\n");
                out.push_str("    ssl_prefer_server_ciphers on;\n");
            }
        }
    }

    // TLS passthrough is handled at stream level, but add a comment
    if first.tls_mode == "passthrough" {
        out.push_str("    # TLS passthrough - should use stream block instead\n");
    }

    out.push('\n');

    // Access list (applied at server level if all rules share the same access list)
    if let Some(acl_id) = &first.access_list_id {
        if let Some((acl, acl_rules)) = access_lists.iter().find(|(l, _)| &l.id == acl_id) {
            out.push_str(&generate_access_directives(acl, acl_rules, "    "));
        }
    }

    // Location blocks for each rule
    for rule in rules {
        let path = rule.path_prefix.as_deref().unwrap_or("/");
        out.push_str(&format!("    location {} {{\n", path));

        let scheme = if rule.tls_mode == "terminate" { "http" } else { "http" };
        out.push_str(&format!(
            "        proxy_pass {}://{}:{};\n",
            scheme, rule.upstream_host, rule.upstream_port
        ));

        out.push_str("        proxy_set_header Host $host;\n");
        out.push_str("        proxy_set_header X-Real-IP $remote_addr;\n");
        out.push_str(
            "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n",
        );
        out.push_str("        proxy_set_header X-Forwarded-Proto $scheme;\n");

        // WebSocket support
        if rule.websocket {
            out.push_str("        proxy_http_version 1.1;\n");
            out.push_str("        proxy_set_header Upgrade $http_upgrade;\n");
            out.push_str(
                "        proxy_set_header Connection \"upgrade\";\n",
            );
        }

        // Custom headers
        if let Some(headers_json) = &rule.custom_headers {
            if let Ok(headers) =
                serde_json::from_str::<std::collections::HashMap<String, String>>(headers_json)
            {
                for (key, value) in &headers {
                    out.push_str(&format!(
                        "        proxy_set_header {} {};\n",
                        key, value
                    ));
                }
            }
        }

        // Per-location access list if different from server-level
        if rule.access_list_id != first.access_list_id {
            if let Some(acl_id) = &rule.access_list_id {
                if let Some((acl, acl_rules)) =
                    access_lists.iter().find(|(l, _)| &l.id == acl_id)
                {
                    out.push_str(&generate_access_directives(acl, acl_rules, "        "));
                }
            }
        }

        out.push_str("    }\n\n");
    }

    out.push_str("}\n");
    out
}

fn generate_access_directives(acl: &AccessList, rules: &[AccessRule], indent: &str) -> String {
    let mut out = String::new();
    for rule in rules {
        let directive = if rule.action == "allow" { "allow" } else { "deny" };
        out.push_str(&format!("{}{} {};\n", indent, directive, rule.ip_cidr));
    }
    let default = if acl.default_policy == "allow" {
        "allow all"
    } else {
        "deny all"
    };
    out.push_str(&format!("{}{};\n", indent, default));
    out
}
