use std::path::Path;

use super::nginx_path;

/// Generate the main nginx.conf content.
pub fn generate_main_config(data_dir: &Path) -> String {
    let dir = nginx_path(data_dir);
    format!(
        r#"# Auto-generated by Meridian. Do not edit manually.
worker_processes auto;
pid "{dir}/nginx/nginx.pid";
error_log "{dir}/nginx/logs/error.log";

events {{
    worker_connections 1024;
}}

http {{
    # Temp directories (override compile-time defaults)
    client_body_temp_path "{dir}/nginx/temp/client_body";
    proxy_temp_path "{dir}/nginx/temp/proxy";

    log_format meridian escape=json
      '{{"time":"$time_iso8601",'
      '"remote_addr":"$remote_addr",'
      '"method":"$request_method",'
      '"uri":"$request_uri",'
      '"status":$status,'
      '"body_bytes_sent":$body_bytes_sent,'
      '"request_time":$request_time,'
      '"upstream_response_time":"$upstream_response_time",'
      '"host":"$host"}}';

    access_log "{dir}/nginx/logs/access.log";

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 100m;

    # MIME types
    default_type application/octet-stream;

    include "{dir}/nginx/conf.d/*.conf";
}}

stream {{
    log_format stream_meridian
      '{{"time":"$time_iso8601",'
      '"remote_addr":"$remote_addr",'
      '"protocol":"$protocol",'
      '"status":$status,'
      '"bytes_sent":$bytes_sent,'
      '"bytes_received":$bytes_received,'
      '"session_time":"$session_time"}}';

    include "{dir}/nginx/stream.d/*.conf";
}}
"#,
        dir = dir,
    )
}
