use std::path::Path;

/// Generate the main nginx.conf content.
pub fn generate_main_config(data_dir: &Path) -> String {
    let dir = data_dir.to_string_lossy();
    format!(
        r#"# Auto-generated by Meridian. Do not edit manually.
worker_processes auto;
pid "{dir}/nginx/nginx.pid";
error_log "{dir}/nginx/logs/error.log";

events {{
    worker_connections 1024;
}}

http {{
    access_log "{dir}/nginx/logs/access.log";

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 100m;

    # MIME types
    default_type application/octet-stream;

    include "{dir}/nginx/conf.d/*.conf";
}}

stream {{
    include "{dir}/nginx/stream.d/*.conf";
}}
"#,
        dir = dir,
    )
}
