use std::path::Path;

use super::nginx_path;

/// Generate the main nginx.conf content.
///
/// `worker_processes` controls the number of nginx worker processes.
/// Accepts "auto" or a numeric string (e.g. "2"). Defaults to "2".
pub fn generate_main_config(data_dir: &Path, worker_processes: &str) -> String {
    let dir = nginx_path(data_dir);
    // Validate: must be "auto" or a positive integer
    let wp = if worker_processes == "auto" {
        "auto".to_string()
    } else {
        worker_processes
            .parse::<u32>()
            .unwrap_or(2)
            .max(1)
            .to_string()
    };
    format!(
        r#"# Auto-generated by Meridian. Do not edit manually.
worker_processes {wp};
pid "{dir}/nginx/nginx.pid";
error_log "{dir}/nginx/logs/error.log";

events {{
    worker_connections 1024;
}}

http {{
    # Temp directories (override compile-time defaults)
    client_body_temp_path "{dir}/nginx/temp/client_body";
    proxy_temp_path "{dir}/nginx/temp/proxy";

    log_format meridian escape=json
      '{{"time":"$time_iso8601",'
      '"remote_addr":"$remote_addr",'
      '"method":"$request_method",'
      '"uri":"$request_uri",'
      '"status":$status,'
      '"body_bytes_sent":$body_bytes_sent,'
      '"request_time":$request_time,'
      '"upstream_response_time":"$upstream_response_time",'
      '"host":"$host"}}';

    access_log "{dir}/nginx/logs/access.log";

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 100m;

    # MIME types
    default_type application/octet-stream;

    include "{dir}/nginx/conf.d/*.conf";
}}

stream {{
    log_format stream_meridian
      '{{"time":"$time_iso8601",'
      '"remote_addr":"$remote_addr",'
      '"protocol":"$protocol",'
      '"status":$status,'
      '"bytes_sent":$bytes_sent,'
      '"bytes_received":$bytes_received,'
      '"session_time":"$session_time"}}';

    include "{dir}/nginx/stream.d/*.conf";
}}
"#,
        dir = dir,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_main_config_has_required_sections() {
        let data_dir = PathBuf::from("/tmp/test");
        let config = generate_main_config(&data_dir, "2");
        assert!(config.contains("worker_processes 2;"));
        assert!(config.contains("http {"));
        assert!(config.contains("stream {"));
        assert!(config.contains("include"));
        assert!(config.contains("conf.d/*.conf"));
        assert!(config.contains("stream.d/*.conf"));
    }

    #[test]
    fn test_main_config_has_json_log_format() {
        let data_dir = PathBuf::from("/tmp/test");
        let config = generate_main_config(&data_dir, "auto");
        assert!(config.contains("worker_processes auto;"));
        assert!(config.contains("log_format"));
        assert!(config.contains("meridian"));
    }
}
