use std::path::Path;

use super::{nginx_path, nginx_path_str};
use crate::store::models::{Certificate, ProxyRule};

#[derive(serde::Deserialize)]
struct UpstreamTarget {
    host: String,
    port: u16,
    weight: Option<u32>,
}

fn parse_upstream_targets(json: &str) -> Option<Vec<UpstreamTarget>> {
    serde_json::from_str::<Vec<UpstreamTarget>>(json).ok().filter(|v| !v.is_empty())
}

fn upstream_name(rule_id: &str) -> String {
    let short = if rule_id.len() > 12 {
        &rule_id[rule_id.len() - 12..]
    } else {
        rule_id
    };
    format!("upstream_{}", short.replace('-', "_"))
}

/// Generate an nginx stream server block for a TCP or UDP proxy rule.
pub fn generate_stream_block(rule: &ProxyRule, certs: &[Certificate], data_dir: &Path) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by Meridian. Do not edit manually.\n");

    // Generate upstream block if multiple targets
    let has_upstream = rule.upstream_targets.as_deref()
        .and_then(|j| parse_upstream_targets(j))
        .is_some();
    if has_upstream {
        if let Some(targets) = rule.upstream_targets.as_deref().and_then(|j| parse_upstream_targets(j)) {
            let name = upstream_name(&rule.id);
            out.push_str(&format!("upstream {} {{\n", name));
            for t in &targets {
                let weight_str = t.weight.map_or(String::new(), |w| format!(" weight={}", w));
                out.push_str(&format!("    server {}:{}{};\n", t.host, t.port, weight_str));
            }
            out.push_str("}\n\n");
        }
    }
    out.push_str("server {\n");

    // Per-rule access log for monitoring metrics
    let log_path = data_dir.join(format!("nginx/logs/rule_{}.access.log", rule.id));
    out.push_str(&format!(
        "    access_log \"{}\" stream_meridian;\n",
        nginx_path(&log_path)
    ));

    let mut listen_directive = format!("    listen {}", rule.listen_port);

    if rule.proxy_type == "stream_udp" {
        listen_directive.push_str(" udp");
    }

    // TLS passthrough or termination at stream level
    if rule.tls_mode == "terminate" {
        listen_directive.push_str(" ssl");
    }

    listen_directive.push_str(";\n");
    out.push_str(&listen_directive);

    // SSL certificates for stream termination
    if rule.tls_mode == "terminate" {
        if let Some(cert_id) = &rule.certificate_id {
            if let Some(cert) = certs.iter().find(|c| &c.id == cert_id) {
                out.push_str(&format!("    ssl_certificate \"{}\";\n", nginx_path_str(&cert.cert_path)));
                out.push_str(&format!("    ssl_certificate_key \"{}\";\n", nginx_path_str(&cert.key_path)));
                out.push_str("    ssl_protocols TLSv1.2 TLSv1.3;\n");
            }
        }
    }

    // TLS passthrough uses ssl_preread
    if rule.tls_mode == "passthrough" {
        out.push_str("    ssl_preread on;\n");
    }

    if has_upstream {
        let name = upstream_name(&rule.id);
        out.push_str(&format!("    proxy_pass {};\n", name));
    } else {
        out.push_str(&format!(
            "    proxy_pass {}:{};\n",
            rule.upstream_host, rule.upstream_port
        ));
    }

    // Timeouts
    out.push_str("    proxy_connect_timeout 10s;\n");
    out.push_str("    proxy_timeout 300s;\n");

    out.push_str("}\n");
    out
}
