use std::path::Path;

use super::{nginx_path, nginx_path_str};
use crate::store::models::{Certificate, ProxyRule};

#[derive(serde::Deserialize)]
struct UpstreamTarget {
    host: String,
    port: u16,
    weight: Option<u32>,
}

fn parse_upstream_targets(json: &str) -> Option<Vec<UpstreamTarget>> {
    serde_json::from_str::<Vec<UpstreamTarget>>(json)
        .ok()
        .filter(|v| !v.is_empty())
}

fn upstream_name(rule_id: &str) -> String {
    let short = if rule_id.len() > 12 {
        &rule_id[rule_id.len() - 12..]
    } else {
        rule_id
    };
    format!("upstream_{}", short.replace('-', "_"))
}

/// Generate an nginx stream server block for a TCP or UDP proxy rule.
pub fn generate_stream_block(rule: &ProxyRule, certs: &[Certificate], data_dir: &Path) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by Meridian. Do not edit manually.\n");

    // Generate upstream block if multiple targets
    let has_upstream = rule
        .upstream_targets
        .as_deref()
        .and_then(|j| parse_upstream_targets(j))
        .is_some();
    if has_upstream {
        if let Some(targets) = rule
            .upstream_targets
            .as_deref()
            .and_then(|j| parse_upstream_targets(j))
        {
            let name = upstream_name(&rule.id);
            out.push_str(&format!("upstream {} {{\n", name));
            for t in &targets {
                let weight_str = t.weight.map_or(String::new(), |w| format!(" weight={}", w));
                out.push_str(&format!(
                    "    server {}:{}{};\n",
                    t.host, t.port, weight_str
                ));
            }
            out.push_str("}\n\n");
        }
    }
    out.push_str("server {\n");

    // Per-rule access log for monitoring metrics
    let log_path = data_dir.join(format!("nginx/logs/rule_{}.access.log", rule.id));
    out.push_str(&format!(
        "    access_log \"{}\" stream_meridian;\n",
        nginx_path(&log_path)
    ));

    let mut listen_directive = format!("    listen {}", rule.listen_port);

    if rule.proxy_type == "stream_udp" {
        listen_directive.push_str(" udp");
    }

    // TLS passthrough or termination at stream level
    if rule.tls_mode == "terminate" {
        listen_directive.push_str(" ssl");
    }

    listen_directive.push_str(";\n");
    out.push_str(&listen_directive);

    // SSL certificates for stream termination
    if rule.tls_mode == "terminate" {
        if let Some(cert_id) = &rule.certificate_id {
            if let Some(cert) = certs.iter().find(|c| &c.id == cert_id) {
                out.push_str(&format!(
                    "    ssl_certificate \"{}\";\n",
                    nginx_path_str(&cert.cert_path)
                ));
                out.push_str(&format!(
                    "    ssl_certificate_key \"{}\";\n",
                    nginx_path_str(&cert.key_path)
                ));
                out.push_str("    ssl_protocols TLSv1.2 TLSv1.3;\n");
            }
        }
    }

    // TLS passthrough uses ssl_preread
    if rule.tls_mode == "passthrough" {
        out.push_str("    ssl_preread on;\n");
    }

    if has_upstream {
        let name = upstream_name(&rule.id);
        out.push_str(&format!("    proxy_pass {};\n", name));
    } else {
        out.push_str(&format!(
            "    proxy_pass {}:{};\n",
            rule.upstream_host, rule.upstream_port
        ));
    }

    // Timeouts
    out.push_str("    proxy_connect_timeout 10s;\n");
    out.push_str("    proxy_timeout 300s;\n");
    if rule.keep_alive {
        out.push_str("    proxy_socket_keepalive on;\n");
    }

    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;

    fn make_stream_rule(keep_alive: bool) -> ProxyRule {
        ProxyRule {
            id: "stream-1".to_string(),
            name: "test".to_string(),
            proxy_type: "stream_tcp".to_string(),
            enabled: true,
            listen_port: 5432,
            listen_host: "0.0.0.0".to_string(),
            domain: None,
            path_prefix: None,
            upstream_host: "127.0.0.1".to_string(),
            upstream_port: 15432,
            upstream_scheme: "http".to_string(),
            tls_mode: "none".to_string(),
            certificate_id: None,
            access_list_id: None,
            websocket: false,
            keep_alive,
            custom_headers: None,
            upstream_targets: None,
            sort_order: 0,
            created_at: "2024-01-01T00:00:00Z".to_string(),
            updated_at: "2024-01-01T00:00:00Z".to_string(),
        }
    }

    #[test]
    fn keep_alive_enables_stream_socket_keepalive() {
        let rule = make_stream_rule(true);
        let config = generate_stream_block(&rule, &[], Path::new("/tmp"));

        assert!(config.contains("    proxy_pass 127.0.0.1:15432;"));
        assert!(config.contains("    proxy_socket_keepalive on;"));
    }
}
