use crate::store::models::{Certificate, ProxyRule};

/// Generate an nginx stream server block for a TCP or UDP proxy rule.
pub fn generate_stream_block(rule: &ProxyRule, certs: &[Certificate]) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by Meridian. Do not edit manually.\n");
    out.push_str("server {\n");

    let mut listen_directive = format!("    listen {}", rule.listen_port);

    if rule.proxy_type == "stream_udp" {
        listen_directive.push_str(" udp");
    }

    // TLS passthrough or termination at stream level
    if rule.tls_mode == "terminate" {
        listen_directive.push_str(" ssl");
    }

    listen_directive.push_str(";\n");
    out.push_str(&listen_directive);

    // SSL certificates for stream termination
    if rule.tls_mode == "terminate" {
        if let Some(cert_id) = &rule.certificate_id {
            if let Some(cert) = certs.iter().find(|c| &c.id == cert_id) {
                out.push_str(&format!("    ssl_certificate \"{}\";\n", cert.cert_path));
                out.push_str(&format!("    ssl_certificate_key \"{}\";\n", cert.key_path));
                out.push_str("    ssl_protocols TLSv1.2 TLSv1.3;\n");
            }
        }
    }

    // TLS passthrough uses ssl_preread
    if rule.tls_mode == "passthrough" {
        out.push_str("    ssl_preread on;\n");
    }

    out.push_str(&format!(
        "    proxy_pass {}:{};\n",
        rule.upstream_host, rule.upstream_port
    ));

    // Timeouts
    out.push_str("    proxy_connect_timeout 10s;\n");
    out.push_str("    proxy_timeout 300s;\n");

    out.push_str("}\n");
    out
}
